import { Link } from "wouter";
import { ArrowRight, Check, ChevronRight, Clock3, ExternalLink, Facebook, MapPin, MessageCircle, Phone, Play, ShieldCheck, Sparkles, Wrench, X } from "lucide-react";
import { useState, type ReactNode } from "react";

export const PHONE = "+234 802 892 0939";
export const PHONE_HREF = "tel:+2348028920939";
export const WA_HREF = "https://wa.me/2348028920939?text=Hello%20Robert%20Power%20Solutions%2C%20I%20need%20help%20with%20my%20solar%20system.";
export const LOGO = "/manus-storage/robert-mark_fb817ed0.png";
export const ROBERT_PHOTO = "/manus-storage/robert-profile-clear_a697fc74.jpg";
export const FIELD_PHOTO = "/manus-storage/solar-installation-field_9df4057e.jpg";
export const FACEBOOK_VIDEO = "https://www.facebook.com/robert.emeka.2025/videos/july-started-proper-with-a-solid-installation/2237703036992293/";
export const X_PROFILE = "https://x.com/RobertSolarspro";

export function Logo() { return <Link href="/" className="logo"><span className="logo-mark"><img src={LOGO} alt="" /></span><span><strong>Robert Power</strong><small>Solutions</small></span></Link>; }

export function Header() {
  const [open, setOpen] = useState(false);
  return <><div className="topline"><div className="container topline-inner"><span>Lagos-based solar service & repairs</span><span className="topline-right"><a href={PHONE_HREF}>{PHONE}</a><span className="top-dot" /> Serving Nigeria by arrangement</span></div></div><header className="header"><div className="container header-inner"><Logo /><button className="mobile-menu" onClick={() => setOpen(v => !v)} aria-label="Toggle menu">{open ? <X /> : <span>Menu</span>}</button><nav className={open ? "nav nav-open" : "nav"}><Link href="/repairs" onClick={() => setOpen(false)}>Repairs</Link><Link href="/installations" onClick={() => setOpen(false)}>Installations</Link><Link href="/about" onClick={() => setOpen(false)}>About</Link><Link href="/case-studies" onClick={() => setOpen(false)}>Case studies</Link><Link href="/contact" onClick={() => setOpen(false)}>Contact</Link><a className="nav-cta" href={WA_HREF} target="_blank" rel="noreferrer"><MessageCircle size={15} /> WhatsApp us</a></nav></div></header></>;
}

export function Footer() { return <footer className="footer"><div className="container footer-grid"><div><Logo /><p className="footer-blurb">Repair-first solar service for homes and businesses. Clear diagnosis, practical work, dependable power.</p><div className="socials"><a href="https://www.facebook.com/robert.emeka.2025/" target="_blank" rel="noreferrer"><Facebook size={15} /></a><a href={X_PROFILE} target="_blank" rel="noreferrer">𝕏</a><a href={WA_HREF} target="_blank" rel="noreferrer"><MessageCircle size={15} /></a></div></div><div className="footer-col"><strong>Explore</strong><Link href="/repairs">Solar repairs</Link><Link href="/installations">Installations</Link><Link href="/about">About Robert</Link><Link href="/contact">Contact</Link></div><div className="footer-col"><strong>Contact</strong><a href={PHONE_HREF}>{PHONE}</a><a href={WA_HREF} target="_blank" rel="noreferrer">WhatsApp Robert</a><span>No. 83 Ijesha Road<br />Lagos, Nigeria</span></div><div className="footer-col"><strong>Legal</strong><Link href="/privacy">Privacy policy</Link><Link href="/terms">Terms & conditions</Link><span className="footer-hours"><Clock3 size={14} /> Mon–Sat · 8am–6pm</span></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Robert Power Solutions</span><span>Built for dependable power</span></div></footer>; }

export function Shell({ children }: { children: ReactNode }) { return <><Header />{children}<Footer /><WhatsAppWidget /></>; }

function WhatsAppWidget() {
  const [open, setOpen] = useState(false);
  const prompts = ["My inverter is beeping", "My batteries are not charging", "I need a solar system", "I want to book a diagnosis"];
  return <div className={`wa-widget ${open ? "wa-widget-open" : ""}`}><div className="wa-panel" aria-hidden={!open}><div className="wa-panel-head"><span className="wa-live-dot" /><div><strong>Robert Power Solutions</strong><small>Usually replies on WhatsApp</small></div><button onClick={() => setOpen(false)} aria-label="Close WhatsApp chat"><X size={16} /></button></div><div className="wa-message"><span className="wa-avatar"><MessageCircle size={16} /></span><p>Hello. What is happening with your solar system?<small>Choose a starting point or write your own message.</small></p></div><div className="wa-prompts">{prompts.map(prompt => <a href={`${WA_HREF}&issue=${encodeURIComponent(prompt)}`} target="_blank" rel="noreferrer" key={prompt}>{prompt}<ArrowRight size={13} /></a>)}</div></div><button className="wa-trigger" onClick={() => setOpen(v => !v)} aria-label="Open WhatsApp chat"><MessageCircle size={19} /><span>{open ? "Close chat" : "Chat with Robert"}</span>{!open && <i>1</i>}</button></div>;
}
export function PageIntro({ eyebrow, title, text }: { eyebrow: string; title: ReactNode; text: string }) { return <section className="page-intro"><div className="page-intro-glow" /><div className="container page-intro-inner"><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{text}</p></div></section>; }
export function ContactStrip() { return <section className="contact-strip"><div className="container contact-strip-inner"><div><span className="eyebrow">NEED HELP NOW?</span><h2>Let’s get your system back on track.</h2></div><div className="contact-actions"><a className="button button-dark" href={WA_HREF} target="_blank" rel="noreferrer"><MessageCircle size={16} /> WhatsApp Robert</a><a className="button button-outline-light" href={PHONE_HREF}><Phone size={15} /> {PHONE}</a></div></div></section>; }

const proofItems = [
  { icon: "01", title: "Diagnose before selling", text: "The first conversation is about the fault, the load, and what the system is doing." },
  { icon: "02", title: "Work with the system you have", text: "Repairs, upgrades, and replacements are considered from the actual equipment in front of you." },
  { icon: "03", title: "Make the next step obvious", text: "You leave with a clear recommendation instead of a cloud of technical jargon." },
  { icon: "04", title: "Stay close after the job", text: "A working system is the goal, not simply a completed invoice." },
];

function ProofWall() { return <section className="proof-wall"><div className="container"><div className="proof-wall-head"><div><div className="eyebrow">THE ROBERT POWER DIFFERENCE</div><h2>Proof you can feel<br /><em>before you buy.</em></h2></div><p>People do not want another solar pitch. They want somebody who can look at the problem, speak plainly, and stand behind the work.</p></div><div className="proof-wall-grid">{proofItems.map(item => <div className="proof-tile" key={item.icon}><span>{item.icon}</span><Sparkles size={17} /><h3>{item.title}</h3><p>{item.text}</p></div>)}</div></div></section>; }

function ClientVoices() { return <section className="voices"><div className="container"><div className="voices-head"><div><div className="eyebrow">PUBLIC FEEDBACK</div><h2>Proof that sounds<br /><em>like real people.</em></h2></div><p>We found these public comments around Robert's repair and installation work. As more customers give permission, this wall can grow into a full named testimonial library.</p></div><div className="voice-grid"><div className="voice-card voice-card-dark"><span className="quote-mark">“</span><p>He sent me a video himself confirming that the inverter is now working perfectly fine.</p><strong>PUBLIC FACEBOOK RECOMMENDATION</strong><small>Repair outcome · Nigeria</small></div><div className="voice-card"><span className="voice-index">01</span><h3>“No complaints, no hidden issues.”</h3><p>Just smooth operation after the repair. That is the outcome every solar owner wants.</p><span className="voice-label">PUBLIC FACEBOOK COMMENT</span></div><div className="voice-card"><span className="voice-index">02</span><h3>“Well done with your services.”</h3><p>Coming from a satisfied client. Short, direct, and exactly the kind of response good work earns.</p><span className="voice-label">PUBLIC INSTAGRAM COMMENT</span></div><div className="voice-card"><span className="voice-index">03</span><h3>Have a real experience?</h3><p>Send Robert your feedback after a repair or installation. With permission, your words can help the next customer decide.</p><a className="arrow-link" href={WA_HREF} target="_blank" rel="noreferrer">Share feedback <ArrowRight size={15} /></a></div></div></div></section>; }
function MediaProof() { return <section className="media-proof"><div className="container"><div className="media-proof-head"><div><div className="eyebrow">REAL WORK · REAL UPDATES</div><h2>See the work<br /><em>in motion.</em></h2></div><p>Watch public installation updates and follow Robert’s latest field work. The best proof is what happens after the promise.</p></div><div className="media-grid"><a className="media-card media-card-large" href={FACEBOOK_VIDEO} target="_blank" rel="noreferrer"><img src={FIELD_PHOTO} alt="Solar panels being prepared for installation" /><span className="media-overlay"><span className="play-button"><Play size={15} fill="currentColor" /></span><span><strong>July started proper with a solid installation</strong><small>Watch public video on Facebook</small></span><ExternalLink size={16} /></span></a><a className="media-card media-card-small" href={X_PROFILE} target="_blank" rel="noreferrer"><img src={ROBERT_PHOTO} alt="Robert Emeka" /><span className="media-overlay"><span className="play-button"><ArrowRight size={15} /></span><span><strong>Follow RobertSolarspro</strong><small>Latest solar work and updates on X</small></span><ExternalLink size={16} /></span></a></div></div></section>; }

export function Home() { return <Shell><section className="home-hero"><div className="hero-grid-lines" /><div className="container home-hero-grid"><div className="home-copy"><div className="eyebrow">SOLAR REPAIRS · INSTALLATIONS · LAGOS</div><h1>Power that feels<br /><em>like relief.</em></h1><p>When your inverter starts beeping, your batteries stop holding charge, or your system simply feels unreliable, Robert Power Solutions helps you get to the real issue.</p><div className="hero-buttons"><a className="button button-coral" href={WA_HREF} target="_blank" rel="noreferrer"><MessageCircle size={16} /> Get repair help <ArrowRight size={16} /></a><Link className="button button-quiet" href="/repairs">See repair services <ArrowRight size={16} /></Link></div><div className="hero-note"><ShieldCheck size={16} /><span><strong>Repair before replacement.</strong> Clear advice, practical work.</span></div></div><div className="hero-media"><div className="hero-media-main"><img src={FIELD_PHOTO} alt="Solar panels being prepared for installation" /><div className="hero-media-label"><span>FIELD NOTE 01</span><strong>Solar installation in progress</strong><small>Lagos, Nigeria</small></div></div><div className="hero-orbit orbit-one" /><div className="hero-orbit orbit-two" /><div className="hero-stat"><strong>01</strong><span>system first<br />sales second</span></div></div></div></section><section className="proof-bar"><div className="container proof-grid"><span>Homes</span><span>Offices</span><span>Shops</span><span>Facilities</span><strong>Lagos → nationwide service by arrangement <ArrowRight size={16} /></strong></div></section><section className="section home-services"><div className="container"><div className="section-heading"><div><div className="eyebrow">WHAT WE DO</div><h2>Solar service without<br /><em>the runaround.</em></h2></div><p>When a solar system is not doing its job, you need someone who can find the fault, explain the options, and do the work properly.</p></div><div className="service-cards"><ServiceCard number="01" title="Inverter repair" text="Diagnostics, board work, error codes, no-output faults, and testing." href="/repairs" /><ServiceCard number="02" title="Battery service" text="Testing, balancing, replacement advice, and backup performance checks." href="/repairs" /><ServiceCard number="03" title="Solar installations" text="Practical solar systems designed for the way your home or business uses power." href="/installations" /></div></div></section><ProofWall /><MediaProof /><ClientVoices /><ContactStrip /></Shell>; }
function ServiceCard({ number, title, text, href }: { number: string; title: string; text: string; href: string }) { return <Link href={href} className="service-card"><span className="service-number">{number}</span><Wrench size={20} /><h3>{title}</h3><p>{text}</p><span className="card-link">Learn more <ArrowRight size={14} /></span></Link>; }

export function Repairs() { return <Shell><PageIntro eyebrow="SOLAR REPAIRS · LAGOS + NIGERIA" title={<>When the power drops, <em>start here.</em></>} text="Repair and maintenance for solar inverters, batteries, panels, charge controllers, wiring, and complete systems." /><section className="section detail-section"><div className="container detail-grid"><div><div className="eyebrow">COMMON PROBLEMS</div><h2>Tell us what your system is doing.</h2><p className="large-copy">You do not need to know the technical name for the fault. Send your location, inverter brand, and a short video or photo of the issue.</p><a className="button button-coral" href={WA_HREF} target="_blank" rel="noreferrer"><MessageCircle size={16} /> Send a WhatsApp message</a></div><div className="problem-list"><Problem title="Inverter faults" text="Beeping, error codes, no output, overloads, overheating, or sudden shutdowns." /><Problem title="Battery problems" text="Poor backup, batteries not charging, fast drain, swelling, or uneven performance." /><Problem title="Low solar production" text="Panels, shading, loose connections, charge controllers, and wiring losses." /><Problem title="Full system servicing" text="A proper health check when the system feels unreliable or performance has changed." /></div></div></section><section className="repair-band"><div className="container repair-band-grid"><div><div className="eyebrow">REPAIR BEFORE REPLACE</div><h2>A fault is not always a new-system problem.</h2></div><p>Robert’s repair-first approach helps you understand whether the issue can be fixed, what it will take, and when replacement is genuinely the more sensible option.</p></div></section><ProofWall /><MediaProof /><ClientVoices /><ContactStrip /></Shell>; }
function Problem({ title, text }: { title: string; text: string }) { return <div className="problem"><span><Check size={15} /></span><div><h3>{title}</h3><p>{text}</p></div></div>; }

export function Installations() { return <Shell><PageIntro eyebrow="SOLAR INSTALLATIONS · HOMES + BUSINESSES" title={<>Build power that fits <em>real life.</em></>} text="Solar systems designed around your load, your budget, and the power reality of where you live and work." /><section className="section detail-section"><div className="container detail-grid"><div><div className="eyebrow">A SYSTEM, NOT A SHOPPING LIST</div><h2>Good installation starts before the first panel goes up.</h2><p className="large-copy">Robert takes time to understand what you need to power, when you need it, and how the system should behave when grid power changes.</p><a className="button button-coral" href={WA_HREF} target="_blank" rel="noreferrer"><MessageCircle size={16} /> Discuss your system</a></div><div className="install-features"><Feature title="Load assessment" text="Understand the devices, appliances, and operating pattern the system needs to support." /><Feature title="System design" text="Choose the right combination of panels, inverter, batteries, protection, and controls." /><Feature title="Professional installation" text="A clean, practical installation with attention to connections, safety, and future service." /><Feature title="Ongoing support" text="Repairs and servicing when you need help keeping the system performing." /></div></div></section><section className="field-photo"><div className="container"><img src={FIELD_PHOTO} alt="Solar panels being prepared for installation" /><div><span className="eyebrow">FROM THE FIELD</span><strong>Solar installations in progress across Nigeria.</strong></div></div></section><MediaProof /><ClientVoices /><ContactStrip /></Shell>; }
function Feature({ title, text }: { title: string; text: string }) { return <div className="feature"><span><Check size={15} /></span><div><h3>{title}</h3><p>{text}</p></div></div>; }

export function About() { return <Shell><PageIntro eyebrow="ABOUT ROBERT POWER SOLUTIONS" title={<>Practical expertise.<br /><em>Power you can trust.</em></>} text="A Lagos-based solar specialist helping homes and businesses get more from the systems they rely on." /><section className="section about-detail"><div className="container about-grid"><div className="about-photo"><img src={ROBERT_PHOTO} alt="Robert Emeka" /><span>Robert Emeka<br /><small>Founder & Solar Specialist</small></span></div><div className="about-copy"><div className="eyebrow">THE PERSON BEHIND THE WORK</div><h2>“I want my clients to enjoy the outcome.”</h2><p>Robert Emeka is an Electrical / Electronics Engineer from COOU and a solar energy specialist. Through Robert Power Solutions, he installs solar systems, repairs inverters, and delivers reliable power solutions for homes and businesses.</p><p>Based in Lagos and available across Nigeria by arrangement, the work is grounded in a simple idea: do the diagnosis properly, communicate clearly, and build systems people can actually depend on.</p><div className="about-facts"><span><strong>COOU</strong><small>Engineering background</small></span><span><strong>Lagos</strong><small>Home base</small></span><span><strong>Nationwide</strong><small>Service by arrangement</small></span></div></div></div></section><ProofWall /><MediaProof /><ClientVoices /><ContactStrip /></Shell>; }

export function Contact() { return <Shell><PageIntro eyebrow="CONTACT ROBERT POWER SOLUTIONS" title={<>Let’s talk about<br /><em>your power.</em></>} text="Tell us what is happening with your system, where you are located, and the best way to reach you." /><section className="section contact-section"><div className="container contact-grid"><div className="contact-details"><div className="contact-item"><span><Phone size={18} /></span><div><small>CALL ROBERT</small><a href={PHONE_HREF}>{PHONE}</a></div></div><div className="contact-item"><span><MessageCircle size={18} /></span><div><small>WHATSAPP</small><a href={WA_HREF} target="_blank" rel="noreferrer">Start a conversation</a></div></div><div className="contact-item"><span><MapPin size={18} /></span><div><small>LOCATION</small><strong>No. 83 Ijesha Road, Lagos</strong><p>Serving Lagos and Nigeria by arrangement.</p></div></div><div className="contact-item"><span><Clock3 size={18} /></span><div><small>AVAILABILITY</small><strong>Monday – Saturday · 8am – 6pm</strong><p>Emergency and out-of-hours requests are handled subject to availability.</p></div></div></div><div className="contact-card"><div className="eyebrow">THE FASTEST WAY TO GET HELP</div><h2>Send the fault<br /><em>on WhatsApp.</em></h2><p>Include your location, inverter brand, what the system is doing, and a photo or short video if you can.</p><a className="button button-dark" href={WA_HREF} target="_blank" rel="noreferrer"><MessageCircle size={16} /> WhatsApp Robert <ArrowRight size={16} /></a><div className="contact-card-note"><Check size={14} /> No pressure. We start with the facts.</div></div></div></section><MediaProof /><ClientVoices /><section className="map-placeholder"><div className="container"><div className="map-card"><MapPin size={24} /><div><strong>Lagos home base</strong><span>No. 83 Ijesha Road, Lagos State, Nigeria</span></div><a href="https://www.google.com/maps/search/?api=1&query=83+Ijesha+Road+Lagos+Nigeria" target="_blank" rel="noreferrer">Open in Maps <ArrowRight size={14} /></a></div></div></section></Shell>; }

export function CaseStudies() { return <Shell><PageIntro eyebrow="CASE STUDIES · REPAIR + INSTALLATION" title={<>The work behind<br /><em>the outcome.</em></>} text="A closer look at the faults, decisions, and practical work that turn unreliable solar systems into dependable power." /><section className="case-intro section"><div className="container case-intro-grid"><div><div className="eyebrow">WHY THIS PAGE EXISTS</div><h2>People trust the process<br /><em>when they can see it.</em></h2></div><p>Every project starts differently. The useful story is not just the equipment list; it is the symptom, the diagnosis, the repair, and what changed for the customer afterwards.</p></div></section><CaseStudy number="01" title="Hybrid inverter fault diagnosis" location="Repair story · Lagos" fault="System beeping, switching off, and refusing to carry the expected load." process="Start with the symptom. Test the inverter, battery bank, connections, and protection points. Isolate the fault before discussing replacement." outcome="A clearer diagnosis, a practical repair path, and a customer who understands what to watch next." /><CaseStudy number="02" title="A complete home power system" location="Installation story · Nigeria" fault="A home needed stable power for everyday appliances without guessing at a shopping list." process="Map the load, understand the usage pattern, size the system around real life, then install with future service in mind." outcome="A system designed around the home’s actual priorities, with a clear route to support after installation." reverse /><section className="before-after-section"><div className="container"><div className="before-after-heading"><div><div className="eyebrow">SEE THE DIFFERENCE</div><h2>From uncertain<br /><em>to understood.</em></h2></div><p>Drag the handle to compare the same field visual in an inspection-style treatment and a finished-work treatment. This is an illustrative demo until Robert adds a matched before-and-after repair pair.</p></div><BeforeAfter /></div></section><MediaProof /><ContactStrip /></Shell>; }

function CaseStudy({ number, title, location, fault, process, outcome, reverse = false }: { number: string; title: string; location: string; fault: string; process: string; outcome: string; reverse?: boolean }) { return <article className={`case-study ${reverse ? "case-study-reverse" : ""}`}><div className="container case-study-grid"><div className="case-study-image"><img src={FIELD_PHOTO} alt="Solar work in progress" /><span className="case-study-number">{number}</span><span className="case-study-caption">FIELD DOCUMENTATION · ROBERTSOLARSPRO</span></div><div className="case-study-copy"><div className="eyebrow">{location}</div><h2>{title}</h2><div className="case-step"><span>THE FAULT</span><p>{fault}</p></div><div className="case-step"><span>THE PROCESS</span><p>{process}</p></div><div className="case-step case-step-outcome"><span>THE OUTCOME</span><p>{outcome}</p></div><a className="arrow-link" href={WA_HREF} target="_blank" rel="noreferrer">Discuss a similar project <ArrowRight size={15} /></a></div></div></article>; }

function BeforeAfter() { const [position, setPosition] = useState(52); return <div className="before-after"><div className="before-after-frame"><img src={FIELD_PHOTO} alt="After treatment showing solar installation work" /><div className="before-layer" style={{ width: `${position}%` }}><img src={FIELD_PHOTO} alt="Before treatment showing a solar installation inspection view" /></div><span className="before-label">BEFORE · INSPECTION</span><span className="after-label">AFTER · FIELD READY</span><div className="slider-handle" style={{ left: `${position}%` }}><span>↔</span></div><input aria-label="Compare before and after images" type="range" min="8" max="92" value={position} onChange={event => setPosition(Number(event.target.value))} /></div><div className="before-after-note"><span><i className="swatch swatch-before" /> Inspection view</span><span><i className="swatch swatch-after" /> Field-ready view</span><small>Illustrative comparison · replace with matched project photos</small></div></div>; }

export function Privacy() { return <LegalPage title="Privacy policy" updated="5 September 2026"><p>This policy explains how Robert Power Solutions handles information you share through this website, WhatsApp, phone, or social media.</p><h2>Information we may receive</h2><p>We may receive your name, phone number, location, equipment details, photographs, videos, and the details you provide about your solar system or service request.</p><h2>How we use information</h2><p>We use this information to respond to enquiries, assess service needs, arrange visits, provide quotes, deliver repairs or installations, and communicate about an active job. We do not sell your personal information.</p><h2>Third-party services</h2><p>When you choose to contact us through WhatsApp, Facebook, X, phone, or another platform, that platform's own privacy policy also applies.</p><h2>Your choices</h2><p>You may ask us to correct or delete personal information we hold about you, subject to any legal or operational requirement to retain it. Contact <a href={WA_HREF} target="_blank" rel="noreferrer">WhatsApp Robert</a> or call {PHONE}.</p></LegalPage>; }
export function Terms() { return <LegalPage title="Terms and conditions" updated="5 September 2026"><p>These terms govern your use of the Robert Power Solutions website and the services arranged through it.</p><h2>Information on this website</h2><p>This website provides general information about solar repairs, servicing, installations, and contact options. It is not a substitute for an on-site assessment.</p><h2>Quotes and scope</h2><p>Any estimate or recommendation is subject to confirmation after the relevant inspection or assessment. The final scope, price, equipment, timing, and warranty terms should be agreed before work begins.</p><h2>Contact</h2><p>Questions can be sent to <a href={WA_HREF} target="_blank" rel="noreferrer">WhatsApp Robert</a> or {PHONE}.</p></LegalPage>; }
function LegalPage({ title, updated, children }: { title: string; updated: string; children: ReactNode }) { return <Shell><section className="legal-hero"><div className="container"><div className="eyebrow">ROBERT POWER SOLUTIONS</div><h1>{title}</h1><p>Last updated {updated}</p></div></section><article className="legal-content container">{children}</article></Shell>; }
export function NotFoundPage() { return <Shell><PageIntro eyebrow="404" title={<>This page is <em>offline.</em></>} text="The page you are looking for does not exist, but Robert can still help with your solar system." /><div className="container not-found"><Link className="button button-coral" href="/">Back to home</Link></div></Shell>; }

function Step({ n, title, text }: { n: string; title: string; text: string }) { return <div className="step"><span>{n}</span><h3>{title}</h3><p>{text}</p></div>; }
function Chevron() { return <ChevronRight size={15} />; }
